### ISSUE TITLE
url unicode verses string error

### ISSUE THREAD

**Issue by ronsawyer777** [ricardobranco777/registry_view#2]
While testing:
$ ./registry_view http://localhost:5000
Image                                                           Id              Created on                      Docker      Compressed Size
Traceback (most recent call last):
  File "./registry_view.py", line 707, in <module>
    main()
  File "./registry_view.py", line 665, in main
    tags = reg.get_tags(repo)
  File "./registry_view.py", line 420, in get_tags
    data = self._get(repo + "/tags/list")
  File "./registry_view.py", line 328, in _get
    body = self._c.get(self._registry + "/v2/" + url, self._headers + headers)
  File "./registry_view.py", line 157, in get
    self.c.setopt(pycurl.URL, url)
TypeError: invalid arguments to setopt

Once I converted the url to a string, worked fine.  Nicely done!

Perhaps it's because I'm using Python 2.7, not 3.x.

**Comment by ricardobranco777** [comment]
Cannot reproduce with Python 2.7.12.  Which versions of Python & PyCurl are you using?
